---
repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint
        types: [yaml]
        args: [-c, ./scripts/pre-commit/yamllint.yml]
        exclude: meta\.yaml$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-json  # checks that all json files have proper syntax
      - id: check-toml  # checks that all toml files have proper syntax
      - id: end-of-file-fixer  # check all files end in a newline
        # handled by clang-format
        exclude_types: [c, c++, cuda]
      - id: pretty-format-json
        args: [--autofix, --indent=4]
      - id: trailing-whitespace  # remove trailing whitespace
        # don't mess up diff files
        exclude: ^src/cmake/patches/.*\.diff$
        # handled by clang-format
        exclude_types: [c, c++, cuda]
      - id: check-symlinks
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.9
    hooks:
      - id: ruff-format
      - id: ruff
        args: ["--config=./pyproject.toml", "--fix"]
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v22.1.2  # Use the sha / tag you want to point at
    hooks:
      - id: clang-format
        files: \.(cu|cuh|h|cc|inl)$
        types_or: []
ci:
  autoupdate_schedule: quarterly
default_language_version:
  python: python3
