repos:
    - repo: https://github.com/PyCQA/isort
      rev: 5.13.2
      hooks:
            - id: isort
    - repo: https://github.com/psf/black
      rev: 24.10.0
      hooks:
            - id: black
    - repo: https://github.com/PyCQA/flake8
      rev: 7.1.1
      hooks:
            - id: flake8
    - repo: https://github.com/pre-commit/mirrors-clang-format
      rev: 'v19.1.2'  # Use the sha / tag you want to point at
      hooks:
        - id: clang-format
          files: \.(cu|cuh|h|cc|inl)$
          types_or: []
default_language_version:
    python: python3
